#!/usr/bin/env python3
"""Rebuild tv_grade.cube as an OWN analytic preset (65^3, trilinear).

The original 17^3 "TV acid grade v7" LUT had unknown provenance, so the file
is regenerated from this project's own documented formula. Everything is done
in gamma-encoded 0..1 RGB space (the space ffmpeg `lut3d` operates in when
applied after `format=gbrp*`).

Preset "TV Acid v8" (this project, MIT):
  - channel slope R 1.020 / G 1.000 / B 0.985, offsets +0.004/+0.001/+0.008
  - contrast S-curve around 0.46, factor 1.12, with highlight soft-knee
  - vibrance-weighted saturation x1.20
  - teal lift in shadows, warm push in highlights
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "tv_grade.cube")
N = 65

CONTRAST = 1.12
PIVOT = 0.46
SAT = 1.20
SLOPE = (1.020, 1.000, 0.985)
OFFSET = (0.004, 0.001, 0.008)
SHADOW_TEAL = (0.000, 0.018, 0.034)
HIGH_WARM = (0.022, 0.009, -0.010)


def soft_knee_hi(x, knee=0.85):
    """Roll off highlights above knee to avoid clipping."""
    if x <= knee:
        return x
    over = x - knee
    return knee + (1.0 - knee) * (1.0 - pow(2.718281828, -over / (1.0 - knee)))


def grade(r, g, b):
    rgb = [r * SLOPE[i] + OFFSET[i] for i, rgbv in enumerate((r, g, b))]
    rgb = [soft_knee_hi(max(0.0, min(1.0, c))) for c in rgb]
    # contrast S-curve around pivot
    rgb = [PIVOT + (c - PIVOT) * CONTRAST for c in rgb]
    luma = 0.2126 * rgb[0] + 0.7152 * rgb[1] + 0.0722 * rgb[2]
    # vibrance: boost less-saturated pixels more
    mx, mn = max(rgb), min(rgb)
    sat0 = mx - mn
    vib = SAT * (1.0 + 0.35 * (1.0 - sat0))
    rgb = [luma + (c - luma) * vib for c in rgb]
    # tints
    sw = max(0.0, 1.0 - luma) ** 2
    hw = max(0.0, luma) ** 2
    for i in range(3):
        rgb[i] += SHADOW_TEAL[i] * sw * 0.8 + HIGH_WARM[i] * hw * 0.6
    return [max(0.0, min(1.0, c)) for c in rgb]


def main():
    lines = [
        'TITLE "Kick Clip Studio - TV Acid v8 (own preset, MIT)"',
        "# Generated by tools/gen_tv_lut.py - rebuild with: python tools/gen_tv_lut.py",
        "LUT_3D_SIZE %d" % N,
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]
    # .cube ordering: red changes fastest
    for b in range(N):
        for g in range(N):
            for r in range(N):
                o = grade(r / (N - 1), g / (N - 1), b / (N - 1))
                lines.append("%.6f %.6f %.6f" % (o[0], o[1], o[2]))
    with open(OUT, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", OUT, "(%d lines, %d^3)" % (len(lines), N))


if __name__ == "__main__":
    main()
